name: "Check & Cachix"

on:
  push:
    branches:
      - main
      - trying
      - staging
      - "feature/darwin-hosts-support"


jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      # TODO: re-enable fail-fast when darwin support is ready
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        submodules: true
        fetch-depth: 0
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          substituters = https://dotfield.cachix.org https://nrdxp.cachix.org https://nix-community.cachix.org https://cache.nixos.org
          trusted-public-keys = dotfield.cachix.org-1:b5H/ucY/9PDARWG9uWA87ZKWUBU+hnfF30amwiXiaNk= nrdxp.cachix.org-1:Fc5PSqY2Jm1TrWfm88l6cvGWwz3s93c6IOifQWnhNW4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - uses: cachix/cachix-action@v10
      with:
        name: dotfield
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # Quick eval
    - run: nix develop --command evalnix

    # Check the digga library
    - run: nix flake check --show-trace

    # Check /examples/*
    # FIXME: requires updates for darwin compatibility
    # - run: nix develop --command -- check-downstream --show-trace
    - run: nix develop --command -- check-groupByConfig --show-trace
    - run: nix develop --command -- check-hmOnly --show-trace
